// Generated by CoffeeScript 1.10.0
(function() {
  var $, _, algebra, component, katex, render, safeParse;

  $ = require('jquery');

  _ = require('underscore');

  katex = require('katex');

  algebra = require('./index');

  component = function(name, values) {
    var key, results, template, value;
    template = $("template#" + name);
    results = [];
    for (key in values) {
      value = values[key];
      results.push($("." + name + "-" + key).textContent(value));
    }
    return results;
  };

  render = function(el, input) {
    var latex, text;
    text = $(el).text();
    if (input == null) {
      input = algebra.parse(text);
    }
    $(el).data('math', text);
    latex = algebra.toLaTeX(input);
    return katex.render(latex, el);
  };

  safeParse = function(input) {
    var error;
    try {
      return parse(input);
    } catch (error) {
      return null;
    }
  };

  $(document).ready(function() {
    var question;
    question = algebra.parse($('#question').text());
    $('.math').each(function(i, el) {
      return render(el);
    });
    $('input').keyup(function() {
      var answer, el;
      answer = safeParse($('input').val());
      if (!answer) {
        return;
      }
      el = $('tr').last().find('td').get(0);
      return render(el, answer);
    });
    $('input').change(function() {
      var answer, box, equation, explanation;
      box = $('tr').last();
      equation = box.find('td').first();
      explanation = box.find('td').last();
      answer = safeParse($('input').val());
      if (!answer) {
        return;
      }
      if (!test(question, answer)) {
        box.addClass('mistake');
        explanation.text('?');
      }
      $('tr.mistake').slice(0, -1).hide();
      return $('#answers').append($('tr').last());
    });
    return $('a').click(function(e) {
      e.preventDefault();
      return $('.mistake').show();
    });
  });

}).call(this);
