// Generated by CoffeeScript 1.10.0
(function() {
  var slice = [].slice;

  exports.needs = function(condition, f) {
    return function(expr) {
      if (condition(expr)) {
        return f(expr);
      } else {
        throw Error();
      }
    };
  };

  exports.modifies = function(condition, f) {
    return function() {
      var expr, options;
      expr = arguments[0], options = 2 <= arguments.length ? slice.call(arguments, 1) : [];
      if (condition(expr)) {
        return f.apply(null, [expr].concat(slice.call(options)));
      } else {
        return expr;
      }
    };
  };

  exports.apply = function(f) {
    return function(args) {
      return f.apply(this, args);
    };
  };

  exports.sum = function(l) {
    return l.reduce(function(a, b) {
      return a + b;
    });
  };

}).call(this);
